server:
  port: 8084

spring:
  application:
    name: API-GATEWAY


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

okta:
  oauth2:
    issuer: https://dev-74305879.okta.com/oauth2/default
    audience: api://default
    client-id: 0oaego5n1ugXPguOI5d7
    client-secret: 9uic_Ejutm-kxeQzhzruyt0sOP7rRu9lJaUCJ_h0jqkY-qiE2a1BBmtQpBKp0l0i
    scopes: openid, profile, email, offline_access