server:
  port: 8083

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: ratingService
  application:
    name: rating-service
  config:
    import: "optional:configserver: http://CONFIG-SERVER"
